spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/survivor?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: admin
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    enabled: true
    contexts: local
    changeLog: classpath:/db/db.changelog-master.xml
  application:
    name: api-survivor

